removed variables

diff --git a/lightweight-infra/post-execution-scripts/db-migration-config.yaml b/lightweight-infra/post-execution-scripts/db-migration-config.yaml
--- a/lightweight-infra/post-execution-scripts/db-migration-config.yaml
+++ b/lightweight-infra/post-execution-scripts/db-migration-config.yaml
@@ -57,7 +57,8 @@ data:
     # Connect to MySQL and create database
     echo "Creating MySQL database '$db_name'..."
     sed -i -E 's/^(SET.*)/-- \1/' $sql_file
-    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" -e "CREATE DATABASE IF NOT EXISTS testing_platform; USE testing_platform; source src/main/resources/db/migration/base_migration_import.sql;" || { echo "Error: Failed to create database"; exit 1; }
+    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" -e "CREATE DATABASE IF NOT EXISTS testing_platform;" || { echo "Error: Failed to create database"; exit 1; }
+    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" -e "USE testing_platform; source src/main/resources/db/migration/base_migration_import.sql;" || { echo "Error: Failed to source database"; exit 1; }
 
     echo "Executing $sql_file in '$db_name' database..."
     mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" testing_platform < "src/main/resources/db/migration/base_migration_import.sql" || { echo "Error: Failed to execute SQL file"; exit 1; }
