added user

diff --git a/lightweight-infra/post-execution-scripts/db-migration-config.yaml b/lightweight-infra/post-execution-scripts/db-migration-config.yaml
--- a/lightweight-infra/post-execution-scripts/db-migration-config.yaml
+++ b/lightweight-infra/post-execution-scripts/db-migration-config.yaml
@@ -24,9 +24,9 @@ data:
 
     # Assign arguments to variables
     git_pat=$1
-    mysql_user=$2
+    mysql_user=root
     mysql_password=$3
-    mysql_url=$4
+    mysql_url=mysql.mysql.svc.cluster.local
 
     # Install property-manager-java-services
     git clone https://$git_pat@github.com/whoosh-labs/property-manager-java-services.git
@@ -57,11 +57,11 @@ data:
     # Connect to MySQL and create database
     echo "Creating MySQL database '$db_name'..."
     sed -i -E 's/^(SET.*)/-- \1/' $sql_file
-    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" --skip-secure-auth -e "CREATE DATABASE IF NOT EXISTS testing_platform;" || { echo "Error: Failed to create database"; exit 1; }
-    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" --skip-secure-auth -e "USE testing_platform; source src/main/resources/db/migration/base_migration_import.sql;" || { echo "Error: Failed to source database"; exit 1; }
+    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" -e "CREATE DATABASE IF NOT EXISTS testing_platform;" || { echo "Error: Failed to create database"; exit 1; }
+    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" -e "USE testing_platform; source src/main/resources/db/migration/base_migration_import.sql;" || { echo "Error: Failed to source database"; exit 1; }
 
     echo "Executing $sql_file in '$db_name' database..."
-    mysql -u"$mysql_user" -p"$mysql_password" --skip-secure-auth -h "$mysql_url" testing_platform < "src/main/resources/db/migration/base_migration_import.sql" || { echo "Error: Failed to execute SQL file"; exit 1; }
+    mysql -u"$mysql_user" -p"$mysql_password" -h "$mysql_url" testing_platform < "src/main/resources/db/migration/base_migration_import.sql" || { echo "Error: Failed to execute SQL file"; exit 1; }
 
     # Write MySQL connection details to env file
     echo "MYSQL_USERNAME=${mysql_user}" >> "${envname}.db.ini"
